# application.yml

# Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user1
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
